version: '3.7'
services:
  postgress:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRESS_DB=app
      - POSTGRESS_USER=app
      - POSTGRESS_PASSWORD=9mREsvXDs9Gk89Ef